### ISSUE TITLE
Styles defined on element are not showing in Styles  tab of Elements.

### ISSUE THREAD

**Issue by rpfeffer** [inspectdev/inspect-issues#35] opened 2021-03-24 16:07 UTC
- inspect-app version: 0.6.1
- OS ARCH VERSION: win32 x64 10.0.19042
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1.start an inspect session.

![image](https://user-images.githubusercontent.com/4060795/112343391-76720180-8c99-11eb-8281-60d8621780ee.png)

**Comment by auchenberg** [comment] 2021-03-25 03:56
Thanks for reporting this @rpfeffer! Duplicate of https://github.com/inspectdev/inspect-issues/issues/19

**Closed as completed by auchenberg** 2021-03-25 03:56 UTC
Labels: duplicate
