### ISSUE TITLE
Feedback from a cancelled trial

### ISSUE THREAD

**Issue by Jimbly** [inspectdev/inspect-issues#93] opened 2021-09-23 16:35 UTC
I tried a quick trial of this in an attempt to debug a page on an iOS 15 device, after all of the free alternatives didn't pan out.  Issues I ran into:
* Docs link on inspect.dev generates an error
* Upon launching Inspect for the first time there was a title off the top of the screen, and a button off the bottom of the screen, and no way to scroll the view, had to resize the window to continue
* After finally getting attached to my running page, any time I stopped in the debugger and tried to continue, the page completely reloaded, defeating any attempt at debugging
* I then tried a simple page instead (`https://get.webgl.org/`), but clicking the "pause" button never paused in the debugger, and the sources tab seemed to not even list the relevant files
* I then completely gave up, cancelled my trial, and ordered a Mac Mini 😠.  Good luck on your project.  Seemed at least a little more functional than the alternatives ^_^.

**Comment by auchenberg** [comment] 2021-11-15 04:55
@Jimbly  Thanks for the feedback, really appreciate it!

1. Should be fixed
2. Fixed in next release
3. We had an issue if you were changing origin. Should be fixed
4. Can't reproduce in the newest build, so hopefully we have this fixed too.

Hope the Mac Mini is great!

**Closed as completed by auchenberg** 2021-11-15 04:55 UTC
