### ISSUE TITLE
Can't edit styles

### ISSUE THREAD

**Issue by phil-lgr** [inspectdev/inspect-issues#25] opened 2021-03-09 19:01 UTC
- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

Honestly I am not sure, 

I was editing 

![image](https://user-images.githubusercontent.com/9644867/110523278-ddab8580-80df-11eb-978f-21ea2b5cf9b8.png)

And then the panel would no longer allow me to add or edit styles

**Comment by auchenberg** [comment] 2021-03-16 16:25
Reproduced and caused by https://github.com/inspectdev/inspect-issues/issues/29. Closing this issue, as it's tracked in the other issue.

**Closed as completed by auchenberg** 2021-03-16 16:25 UTC
Labels: bug
