### ISSUE TITLE
Runs slow when device view is enabled on IOS

### ISSUE THREAD

**Issue by jagoqui** [inspectdev/inspect-issues#175] opened 2023-05-19 19:52 UTC
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: linux x64 6.2.0-2-rt3-MANJARO
- Language: en_US.UTF-8

Steps to Reproduce:

1. Connect IOS(16.1.1) device to Linux PC.
2. Inspect Website 

If it is inspected normally it works smoothly, but if device view is enabled it gets slow.

![image](https://github.com/inspectdev/inspect-issues/assets/53231080/c9f4391b-5ad5-41bb-8805-191cffa6c967)

**Comment by auchenberg** [comment] 2024-01-15 04:43
Duplicate of https://github.com/inspectdev/inspect-issues/issues/127

**Closed as completed by auchenberg** 2024-01-15 04:43 UTC
Labels: duplicate
