### ISSUE TITLE
Inspect does not show page content

### ISSUE THREAD

**Issue by cdionne-mlspin** [inspectdev/inspect-issues#27] opened 2021-03-10 17:09 UTC
- inspect-app version: 0.5.66
- OS ARCH VERSION: win32 x64 10.0.18363
- Electron: 11.2.1
- Language: undefined
Inspecting on iPhone running ios 14.3 Iphone 6s

Steps to Reproduce:

1. Start inspect
2.  Under available devices, cliick on web page running in safari/iphone
3.  in Inpect window, when viewing "elements" tab, the html for page is not listed,  page has doc type of <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
4. This is an older web page, I'm able to view newer web pages with doctype of  <!DOCTYPE html>
5. Inspect is not showing error
![insepect_screenshot](https://user-images.githubusercontent.com/80415316/110668534-6803f000-8199-11eb-959a-5fe77be58a2a.jpg)
s

**Comment by cdionne-mlspin** [comment] 2021-03-10 17:17
I've restarted inspect and now I can see the html .  Not sure why it was not displaying html earlier.

**Comment by auchenberg** [comment] 2021-03-16 16:25
Reproduced and caused by https://github.com/inspectdev/inspect-issues/issues/29. Closing this issue, as it's tracked in the other issue.

**Closed as completed by auchenberg** 2021-03-16 16:25 UTC
Labels: bug
